//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facutly
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facutly()
        {
            this.Classes = new HashSet<Class>();
            this.Salaries = new HashSet<Salary>();
        }
    
        public long Teacher_ID { get; set; }
        public string Teacher_Email { get; set; }
        public string Teacher_Phone { get; set; }
        public string Teacher_Name { get; set; }
        public string Teacher_Address { get; set; }
        public string Teacher_Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Class> Classes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salary> Salaries { get; set; }
    }
}
