//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        public long Fees_Collection_id { get; set; }
        public long Student_ID { get; set; }
        public string Month { get; set; }
        public long Total_Fees { get; set; }
        public long Amount_Paid { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
