//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public long Grade_id { get; set; }
        public long Grade1 { get; set; }
        public long Min_Marks { get; set; }
        public long Max_Marks { get; set; }
    }
}
