//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public long Marks_ID { get; set; }
        public long Student_ID { get; set; }
        public long Class_ID { get; set; }
        public long Assignment_Marks { get; set; }
        public long Quiz_Marks { get; set; }
        public long Mid_Marks { get; set; }
        public long Final_Marks { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Student Student { get; set; }
    }
}
