//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FINALPROJECTEntities1 : DbContext
    {
        public FINALPROJECTEntities1()
            : base("name=FINALPROJECTEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Assignment> Assignments { get; set; }
        public virtual DbSet<Assignment_Submission> Assignment_Submission { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Class_Enrolment> Class_Enrolment { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<Facutly> Facutlies { get; set; }
        public virtual DbSet<Fee> Fees { get; set; }
        public virtual DbSet<Grade> Grades { get; set; }
        public virtual DbSet<Mark> Marks { get; set; }
        public virtual DbSet<Quiz> Quizs { get; set; }
        public virtual DbSet<Quiz_Submission> Quiz_Submission { get; set; }
        public virtual DbSet<Salary> Salaries { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
