//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz_Submission
    {
        public long Quiz_Submission_id { get; set; }
        public long Quiz_ID { get; set; }
        public long Student_ID { get; set; }
        public long Marks_Obtained { get; set; }
    
        public virtual Quiz Quiz { get; set; }
        public virtual Student Student { get; set; }
    }
}
