//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long Acc_ID { get; set; }
        public string Email { get; set; }
        public string password { get; set; }
        public string user_type { get; set; }

        public virtual Student Student { get; set; }
    }
}
